### ISSUE TITLE
critic in "Explaining Explanations: Axiomatic Feature Interactions for Deep Networks"

### ISSUE THREAD

**Issue by Karim-53** [mtsang/archipelago#2]
Hi,

Thanks for this great paper.
I would like to ask you please concerning a critic made in one of the papers citing your publication:
https://www.jmlr.org/papers/volume22/20-1223/20-1223.pdf

> In Tables 1 and 2 of their recent paper, “How does this interaction affect me?: Interpretable attribution for feature interactions,” Tsang et al. (2020) compare their “interaction attribution” method ArchAttribute to Integrated Hessians. We believe this is a faulty comparison.

> We prove why we believe this is a flawed comparison by showing that from a gametheoretic perspective, the value calculated by ArchAttribute corresponds to a Group Shapley Value rather than any sort of interaction value.

> Theorem 2 For a set of features I found using the first two steps of the procedure in Tsang et al. (2020), the ArchAttribute value Φ(I) is exactly the Group Shapley Value.

> the ArchAttribute method appears to be a method for calculating group attributions rather than feature interactions,

Do you think the analysis holds?
Thanks

**Comment by mtsang** [comment]
Hi @Karim-53, thanks for pointing me to this critique. I think the concept of "interaction" has considerable room for interpretation. [My paper](https://proceedings.neurips.cc/paper/2020/file/443dec3062d0286986e21dc0631734c9-Paper.pdf) argued that ArchAttribute is a way of making feature interactions more explainable to normal people. Please take a look at Figure 1 in my paper to understand this argument
